platform :ios do
  before_all do
    setup_circle_ci
  end

  lane :beta do
    match(type: "adhoc")
    build_app(
      xcodeproj: "Builds/iOS/iOS/Unity-iPhone.xcodeproj"
      scheme: "Unity-iPhone",
      configuration: "Debug",
      export_method: "ad-hoc"
    )
  end
end

platform :android do
  lane :beta do
    firebase_app_distribution(
      app: "1:922310892459:android:8d4d80f5c33fc5163e90ee",
      apk_path: "Builds/Android/Android.apk",
    )
  end
end
